### ISSUE TITLE
KeyError: u'HOMEDRIVE' (windows 8.1)

### ISSUE THREAD

**Issue by thansau239** [SekoiaLab/Fastir_Collector#12]
E:\FastIR>FastIR_x64.exe
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\pylibs\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\factory.factory", line 3, in <module>
  File "C:\pylibs\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\settings", line 61, in <module>
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\os", line 425, in **get item**
KeyError: u'HOMEDRIVE'

**Comment by NaykiSec** [comment]
Same error for me on Windows 7 SP1 32bit (with FastIR_x32.exe)

**Comment by sebdraven** [comment]
Yep we fix it this problem with the next release after botconf in simulating the env variable if it doesn't exist

**Comment by DarkSurferZA** [comment]
Not sure if this would be an acceptable fix for everyone, but within the settings.py file, above the "USERS_FOLDER =" definition on line 60, you could append a if else block to check if the the key os.environ['HOMEDRIVE'] exists (if 'HOMEDRIVE' in os.environ:). if it exists, carry on as normal, if not, you could set the key to the default c:\. 
This works well in our setup, but i am not sure what the impact is for everyone.

**Comment by NaykiSec** [comment]
Oh ok i see, i will try that @home to this if it works well.

Thanks @DarkSurferZA :)

**Comment by DarkSurferZA** [comment]
No issues. 

If you are running on a large scale and dont want to compile your own copy of fastir, just run the command "set HOMEDRIVE=c:\" (or which ever drive you are expecting the users home folder) on your windows host prior to starting fastir.

**Comment by masterofoz** [comment]
I had the same problem om my Win 10 system.
The problem was that if I ran a administrative cmd prompt I didn't have the HOMEDRIVE variable set.
If I ran it as a regular user (non-admin cmd prompt) it had the variable so it worked, but I didn't have admin privs when I ran the command.
Solution:
Running "set HOMEDRIVE=c:" in the admin cmd prompt solved the problem.
I also had problem with the command when ran from the build directory did not find the FastIR.conf file.
I solved this by having the executable in the same directory as the .conf file.
