### ISSUE TITLE
Issue with Prefetch results

### ISSUE THREAD

**Issue by bertalma** [SekoiaLab/Fastir_Collector#18]
Hello, 

I have an issue with the prefetch results, in the result file, they are on a single cell one after the other.
It makes it almost impossible to use them. It also trigger an error, excel bein impossible to display all the results ( as it's too much for a single cell).

I can provide sample by mail if required.

Best regards

**Comment by SyBen** [comment]
This issue was due to csv outputs with fields larger than 32767 characters, which is a known excel limitation ([see](https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)).
This issue has been fixed by adding a `--excel` flag and a config option to limit the output fields' size in 1e8872d.
